- name: Execute the validations role
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:

    - name: Run validations
      ansible.builtin.include_role:
        name: validations
